name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --no-suggest --prefer-dist --optimize-autoloader"

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]
        php-versions: ['7.4', '7.3']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Clone/setup composer v2
        run: 'git clone https://github.com/composer/composer.git'

      - name: Build composer v2
        run: "cd composer && composer install ${{ env.COMPOSER_FLAGS }}"

      - name: Validate composer.json and composer.lock
        run: composer/vendor/bin/composer validate

      - name: Install dependencies
        run: "composer/vendor/bin/composer install ${{ env.COMPOSER_FLAGS }}"

      - name: PHP Copy Paste Detector
        uses: StephaneBour/actions-php-cpd@1.0
        with:
          dir: './src'
          args: '--exclude composer vendor'

      - name: PHP Code Style (phpcs)
        uses: chindit/actions-phpcs@master

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Run test suite
        run: vendor/bin/phpunit
